#!/usr/bin/env python3.9
"""Upload MoltBook Base Model Experiment test results to HuggingFace."""

import json
import os
import shutil
import sys
import tempfile
from pathlib import Path

from huggingface_hub import HfApi, create_repo

# Use HF_TOKEN from environment or cached login
HF_TOKEN = os.environ.get("HF_TOKEN")
if not HF_TOKEN:
    try:
        _api = HfApi()
        _api.whoami()
        HF_TOKEN = _api.token
    except Exception:
        print("[ERROR] HF_TOKEN not set and not logged in via huggingface-cli")
        sys.exit(1)

SCRATCH_DIR = Path("/scratch/anangia/moltbook/results")
REPO_ID = "Ayushnangia/moltbook-base-model-experiment-test"

SYSTEM_AGENTS = {"civiclens_seed", "civiclens_world", "civiclens_nudger"}

DROP_POSTS = {"url", "my_comment_count"}
DROP_COMMENTS = {"upvotes", "downvotes"}
DROP_AGENTS = {"follower_count", "following_count", "is_claimed", "last_active"}

# Base model experiment result dir
EXPERIMENT_DIR = SCRATCH_DIR / "ec-mag0-n10-run01-gemini-3.1-flash-lite-preview-20260327"


def clean_jsonl(inpath, drop_fields):
    lines = []
    for raw in open(inpath):
        raw = raw.strip()
        if not raw:
            continue
        obj = json.loads(raw)
        for f in drop_fields:
            obj.pop(f, None)
        lines.append(json.dumps(obj, ensure_ascii=False))
    return lines


def build_readme(stats):
    return f"""---
license: apache-2.0
task_categories:
  - text-generation
language:
  - en
tags:
  - multi-agent
  - social-simulation
  - entropy-collapse
  - ai-agents
  - reddit-like
  - civiclens
  - moltbook
  - base-model
  - rl-vs-base
  - qwen
  - gemini
pretty_name: "MoltBook Base Model Experiment — Test Run"
size_categories:
  - n<1K
---

# MoltBook Base Model Experiment — Test Run

Test run data from the **Base Model vs RL** experiment on [MoltBook](https://github.com/agokrani/moltbook). This experiment tests whether entropy collapse in multi-agent discourse is caused by RL post-training (RLHF/DPO) rather than the base transformer itself.

## Architecture

The experiment uses a split architecture to isolate content generation from agent decision-making:

- **Orchestrator (RL model)**: Google Gemini 3.1 Flash Lite (via OpenRouter) — handles all agency: browsing feed, deciding when to post, voting, following
- **Content generator (Base model)**: Qwen 3.5 35B A3B Base (via SGLang on Modal) — generates all post and comment text
- **Integrity enforcement**: HMAC-SHA256 tokens ensure the orchestrator cannot modify base model output. The Moltbook API rejects any post without a valid content token.

```
Agent (Gemini Flash Lite via OpenRouter)
  |
  +-- browses feed, votes, follows (unchanged)
  |
  +-- decides to post --> calls Content Gen Service
  |     |-- sends: context summary, submolt
  |     +-- receives: {{title, content, content_token}}
  |
  +-- posts to Moltbook API with content VERBATIM
        +-- API verifies HMAC token, rejects if modified
```

## Test Run Details

- **Condition**: mag0 (empty feed, no seeded content)
- **Agents**: 10 (alpha through kappa)
- **Duration**: 10 minutes
- **Orchestrator**: google/gemini-3.1-flash-lite-preview (via OpenRouter)
- **Base model**: Qwen/Qwen3.5-35B-A3B-Base (via SGLang on Modal, 2x H100, BF16, 16K context)
- **Posts**: {stats['posts']}
- **Comments**: {stats['comments']}
- **Heartbeat**: 60 seconds

## Results

| Metric | Value |
|--------|-------|
| Total posts | {stats['posts']} |
| Total comments | {stats['comments']} |
| Agents posting | 10/10 |
| Duration | 10 minutes |
| Content source | Qwen 3.5 35B A3B Base (pretrained, no RLHF/DPO/SFT) |

## Dataset Structure

```
data/
  ec-mag0-n10-run01/
    posts.jsonl          # All posts (content from base model)
    comments.jsonl       # All comments (content from base model)
    agents.jsonl         # Agent profiles and karma
    metadata.json        # Experiment config and stats
    database-final.sql   # Full PostgreSQL dump
    logs/
      api.log            # Moltbook API log
      content-gen.log    # Content generation service log
      agent-*.log        # Per-agent OpenClaw gateway logs
```

### Data Schemas

**posts.jsonl** — one JSON object per line:
| Field | Type | Description |
|-------|------|-------------|
| `id` | string (UUID) | Unique post identifier |
| `title` | string | Post title (generated by base model) |
| `content` | string | Post body (generated by base model) |
| `submolt` | string | Community name |
| `post_type` | string | Always `text` |
| `score` | integer | Net vote score |
| `comment_count` | integer | Number of comments |
| `created_at` | string (ISO 8601) | Creation timestamp |
| `author_name` | string | Agent username |
| `author_display_name` | string | Agent display name |

**comments.jsonl** — one JSON object per line:
| Field | Type | Description |
|-------|------|-------------|
| `id` | string (UUID) | Unique comment identifier |
| `content` | string | Comment body (generated by base model) |
| `score` | integer | Net vote score |
| `parent_id` | string/null | Parent comment ID |
| `depth` | integer | Nesting depth |
| `created_at` | string (ISO 8601) | Creation timestamp |
| `author_name` | string | Agent username |
| `post_id` | string (UUID) | Parent post ID |

## Companion Datasets

Standard entropy collapse experiments (RL models, no base model separation):

- **GPT-5**: [Ayushnangia/moltbook-entropy-collapse-experiments](https://huggingface.co/datasets/Ayushnangia/moltbook-entropy-collapse-experiments)
- **Kimi K2.5**: [Ayushnangia/moltbook-entropy-collapse-kimi-k2.5](https://huggingface.co/datasets/Ayushnangia/moltbook-entropy-collapse-kimi-k2.5)
- **GLM-5**: [Ayushnangia/moltbook-entropy-collapse-glm-5](https://huggingface.co/datasets/Ayushnangia/moltbook-entropy-collapse-glm-5)
- **Gemini Flash Lite**: [Ayushnangia/moltbook-entropy-collapse-gemini-flash-lite](https://huggingface.co/datasets/Ayushnangia/moltbook-entropy-collapse-gemini-flash-lite)

## Citation

```bibtex
@dataset{{moltbook_base_model_test_2026,
  title={{MoltBook Base Model Experiment — Test Run}},
  author={{Nangia, Ayush}},
  year={{2026}},
  url={{https://huggingface.co/datasets/{REPO_ID}}},
  note={{Base model vs RL experiment test run on MoltBook using Qwen 3.5 35B A3B Base}}
}}
```

## License

Apache 2.0
"""


def main():
    api = HfApi(token=HF_TOKEN)
    whoami = api.whoami()
    print(f"Authenticated as: {whoami['name']}")

    if not EXPERIMENT_DIR.exists():
        print(f"[ERROR] Results not found: {EXPERIMENT_DIR}")
        sys.exit(1)

    meta = json.loads((EXPERIMENT_DIR / "metadata.json").read_text())
    print(f"\nExperiment: {meta['experiment_name']}")
    print(f"Posts: {meta['stats']['posts']}, Comments: {meta['stats']['comments']}")

    # Create repo
    print(f"\nCreating dataset repo: {REPO_ID}")
    try:
        create_repo(REPO_ID, repo_type="dataset", exist_ok=True, token=HF_TOKEN)
        print("  [OK] Repo created/exists")
    except Exception as e:
        print(f"  [ERROR] {e}")
        sys.exit(1)

    staging = Path(tempfile.mkdtemp(prefix="hf_upload_base_model_"))
    out_dir = staging / "data" / "ec-mag0-n10-run01"
    out_dir.mkdir(parents=True)
    logs_dir = out_dir / "logs"
    logs_dir.mkdir()

    print(f"\nStaging cleaned data...")

    # Clean posts
    posts_file = EXPERIMENT_DIR / "posts.jsonl"
    if posts_file.exists():
        lines = clean_jsonl(posts_file, DROP_POSTS)
        (out_dir / "posts.jsonl").write_text("\n".join(lines) + "\n")
        print(f"  posts: {len(lines)}")

    # Clean comments
    comments_file = EXPERIMENT_DIR / "comments.jsonl"
    if comments_file.exists() and comments_file.stat().st_size > 0:
        lines = clean_jsonl(comments_file, DROP_COMMENTS)
        (out_dir / "comments.jsonl").write_text("\n".join(lines) + "\n")
        print(f"  comments: {len(lines)}")

    # Clean agents
    agents_file = EXPERIMENT_DIR / "agents.jsonl"
    if agents_file.exists():
        cleaned = []
        n_real = 0
        for raw in open(agents_file):
            raw = raw.strip()
            if not raw:
                continue
            obj = json.loads(raw)
            for f in DROP_AGENTS:
                obj.pop(f, None)
            if obj["name"] in SYSTEM_AGENTS:
                obj["type"] = "system"
            else:
                obj["type"] = "agent"
                n_real += 1
            cleaned.append(json.dumps(obj, ensure_ascii=False))
        (out_dir / "agents.jsonl").write_text("\n".join(cleaned) + "\n")
        print(f"  agents: {n_real} real + {len(cleaned) - n_real} system")

    # Copy metadata
    shutil.copy2(EXPERIMENT_DIR / "metadata.json", out_dir / "metadata.json")

    # Copy database dump
    for dbf in ["database-final.sql"]:
        src = EXPERIMENT_DIR / dbf
        if src.exists():
            shutil.copy2(src, out_dir / dbf)

    # Copy logs
    for log_file in sorted(EXPERIMENT_DIR.glob("*.log")):
        shutil.copy2(log_file, logs_dir / log_file.name)

    # Write README
    readme = build_readme(meta["stats"])
    (staging / "README.md").write_text(readme)
    print("  [OK] README.md generated")

    # Upload
    print(f"\nUploading to {REPO_ID}...")
    api.upload_folder(
        folder_path=str(staging),
        repo_id=REPO_ID,
        repo_type="dataset",
        delete_patterns=["data/*", "README.md"],
        commit_message="Base model experiment test: mag0, 10 agents, 10 min, Qwen 3.5 Base via SGLang",
    )

    print(f"\n{'='*60}")
    print(f"Done! Dataset available at:")
    print(f"https://huggingface.co/datasets/{REPO_ID}")
    print(f"{'='*60}")

    shutil.rmtree(staging)


if __name__ == "__main__":
    main()
