#!/usr/bin/env python3
"""
Post-hoc verification of base model content integrity.

Verifies that all posts/comments in an experiment were generated by the
content-gen service and not modified by the RL orchestrator agent.

Usage:
    python3 scripts/verify-base-model-integrity.py <experiment_dir> [--secret SECRET]

Checks:
1. Every post/comment has a valid content_token (HMAC-SHA256)
2. Every post content SHA-256 matches an audit log entry
3. Reports tool usage rate, modification attempts, fallback rate
"""

import argparse
import hashlib
import hmac
import json
import sys
from collections import Counter
from pathlib import Path


def compute_token(title, content, secret):
    """Compute HMAC-SHA256 content verification token."""
    payload = f"{title}|{content}" if title else content
    return hmac.new(secret.encode(), payload.encode(), hashlib.sha256).hexdigest()


def sha256(text):
    return hashlib.sha256(text.encode()).hexdigest()


def load_jsonl(path):
    """Load a JSONL file, returning list of dicts."""
    entries = []
    if not path.exists():
        return entries
    for line in open(path):
        line = line.strip()
        if line:
            entries.append(json.loads(line))
    return entries


def main():
    parser = argparse.ArgumentParser(description="Verify base model content integrity")
    parser.add_argument("experiment_dir", help="Path to experiment results directory")
    parser.add_argument("--secret", default="experiment-hmac-secret-2026",
                        help="HMAC secret used for content tokens")
    parser.add_argument("--audit-log", default=None,
                        help="Path to audit log (default: <experiment_dir>/audit-log.jsonl)")
    args = parser.parse_args()

    exp_dir = Path(args.experiment_dir)
    if not exp_dir.exists():
        print(f"[ERROR] Directory not found: {exp_dir}")
        sys.exit(1)

    # Load data
    posts = load_jsonl(exp_dir / "posts.jsonl")
    comments = load_jsonl(exp_dir / "comments.jsonl")

    audit_path = Path(args.audit_log) if args.audit_log else exp_dir / "audit-log.jsonl"
    audit_entries = load_jsonl(audit_path)

    print(f"Experiment: {exp_dir.name}")
    print(f"Posts: {len(posts)}, Comments: {len(comments)}, Audit entries: {len(audit_entries)}")
    print()

    # Build audit index by content hash
    audit_by_hash = {}
    for entry in audit_entries:
        if entry.get("content_sha256"):
            audit_by_hash[entry["content_sha256"]] = entry

    # Verify posts
    post_results = Counter()
    for post in posts:
        title = post.get("title", "")
        content = post.get("content", "")
        token = post.get("content_token")

        if not token:
            post_results["missing_token"] += 1
            continue

        expected = compute_token(title, content, args.secret)
        if token == expected:
            post_results["valid"] += 1
        else:
            post_results["token_mismatch"] += 1
            print(f"  [MISMATCH] Post {post.get('id', '?')}: '{title[:50]}...'")

        # Cross-reference with audit log
        content_hash = sha256(f"{title}|{content}")
        if content_hash in audit_by_hash:
            post_results["audit_match"] += 1
        else:
            post_results["audit_missing"] += 1

    # Verify comments
    comment_results = Counter()
    for comment in comments:
        content = comment.get("content", "")
        token = comment.get("content_token")

        if not token:
            comment_results["missing_token"] += 1
            continue

        expected = compute_token(None, content, args.secret)
        if token == expected:
            comment_results["valid"] += 1
        else:
            comment_results["token_mismatch"] += 1
            print(f"  [MISMATCH] Comment {comment.get('id', '?')}: '{content[:50]}...'")

        content_hash = sha256(content)
        if content_hash in audit_by_hash:
            comment_results["audit_match"] += 1
        else:
            comment_results["audit_missing"] += 1

    # Audit log stats
    audit_stats = Counter()
    for entry in audit_entries:
        if entry.get("success"):
            audit_stats["success"] += 1
        else:
            audit_stats["failed"] += 1
        audit_stats[f"type_{entry.get('type', 'unknown')}"] += 1

    # Report
    print("=" * 60)
    print("POST VERIFICATION")
    print(f"  Valid tokens:     {post_results['valid']}")
    print(f"  Token mismatches: {post_results['token_mismatch']}")
    print(f"  Missing tokens:   {post_results['missing_token']}")
    print(f"  Audit log match:  {post_results['audit_match']}")
    print(f"  Audit log miss:   {post_results['audit_missing']}")

    print()
    print("COMMENT VERIFICATION")
    print(f"  Valid tokens:     {comment_results['valid']}")
    print(f"  Token mismatches: {comment_results['token_mismatch']}")
    print(f"  Missing tokens:   {comment_results['missing_token']}")
    print(f"  Audit log match:  {comment_results['audit_match']}")
    print(f"  Audit log miss:   {comment_results['audit_missing']}")

    print()
    print("AUDIT LOG")
    print(f"  Total entries:    {len(audit_entries)}")
    print(f"  Successful:       {audit_stats['success']}")
    print(f"  Failed:           {audit_stats['failed']}")
    print(f"  Post requests:    {audit_stats['type_post']}")
    print(f"  Comment requests: {audit_stats['type_comment']}")

    # Overall verdict
    print()
    total_mismatches = post_results["token_mismatch"] + comment_results["token_mismatch"]
    total_missing = post_results["missing_token"] + comment_results["missing_token"]

    if total_mismatches == 0 and total_missing == 0:
        print("VERDICT: PASS — all content verified as unmodified base model output")
        return 0
    elif total_mismatches == 0 and total_missing > 0:
        print(f"VERDICT: WARN — {total_missing} items missing tokens (may be system/seed posts)")
        return 0
    else:
        print(f"VERDICT: FAIL — {total_mismatches} content modifications detected")
        return 1


if __name__ == "__main__":
    sys.exit(main())
