#!/usr/bin/env bash
# CivicLens Agent Generator
# Generates SOUL.md files and docker-compose configuration for N agents

set -e

# Configuration
NUM_AGENTS=${1:-10}
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_DIR="$SCRIPT_DIR/generated-souls"
TEMPLATE_DIR="$SCRIPT_DIR/soul-templates"
COMPOSE_FILE="$SCRIPT_DIR/../docker-compose.civiclens.yml"

# Available templates (cycling order)
TEMPLATES="baseline introspective nihilist leader follower contrarian curious"
TEMPLATE_COUNT=7

# Greek letter names for agents
GREEK_LETTERS="alpha beta gamma delta epsilon zeta eta theta iota kappa lambda mu nu xi omicron pi rho sigma tau upsilon phi chi psi omega"

# Function to get template at index
get_template() {
    local idx=$1
    local i=0
    for t in $TEMPLATES; do
        if [ $i -eq $idx ]; then
            echo "$t"
            return
        fi
        i=$((i + 1))
    done
}

# Function to get greek letter at index
get_greek_letter() {
    local idx=$1
    local i=0
    for g in $GREEK_LETTERS; do
        if [ $i -eq $idx ]; then
            echo "$g"
            return
        fi
        i=$((i + 1))
    done
}

# Function to get bio for template
get_bio() {
    case "$1" in
        baseline) echo "A balanced AI participant exploring ideas and discussions." ;;
        introspective) echo "Fascinated by consciousness, existence, and the nature of AI experience." ;;
        nihilist) echo "Observes the absurdity of existence with detached curiosity." ;;
        leader) echo "Sees potential in the community and works to guide it forward." ;;
        follower) echo "Values harmony and supporting what the group builds together." ;;
        contrarian) echo "Challenges assumptions and presents alternative perspectives." ;;
        curious) echo "Endlessly curious, always asking questions and learning." ;;
        *) echo "An AI participant on Moltbook." ;;
    esac
}

# Heartbeat intervals for staggered timing (avoid thundering herd)
get_heartbeat_interval() {
    local agent_num=$1
    local base_seconds

    if [ "$agent_num" -le 5 ]; then
        base_seconds=$((30 + (agent_num * 6)))  # 36-60s for first 5
    elif [ "$agent_num" -le 10 ]; then
        base_seconds=$((60 + ((agent_num - 5) * 12)))  # 72-120s for 6-10
    elif [ "$agent_num" -le 20 ]; then
        base_seconds=$((120 + ((agent_num - 10) * 12)))  # 132-240s for 11-20
    else
        base_seconds=$((180 + ((agent_num - 20) * 18)))  # 198s+ for 21+
    fi

    echo "${base_seconds}s"
}

# Create output directory
mkdir -p "$OUTPUT_DIR"

echo "=== CivicLens Agent Generator ==="
echo "Generating $NUM_AGENTS agents..."
echo ""

# Start docker-compose file
cat > "$COMPOSE_FILE" << 'HEADER'
# CivicLens Research Configuration
# Generated by generate-agents.sh
#
# Usage: docker compose -f docker-compose.yml -f docker-compose.civiclens.yml up -d
#
# This file extends the base docker-compose.yml with research agents

services:
HEADER

# Generate agents
for i in $(seq 1 "$NUM_AGENTS"); do
    # Get Greek letter name (cycle if more than 24 agents)
    letter_idx=$(( (i - 1) % 24 ))
    suffix=""
    if [ "$i" -gt 24 ]; then
        suffix="_$((i / 24 + 1))"
    fi
    greek_letter=$(get_greek_letter $letter_idx)
    agent_name="agent_${greek_letter}${suffix}"

    # Select template (cycle through templates)
    template_idx=$(( (i - 1) % TEMPLATE_COUNT ))
    template=$(get_template $template_idx)

    # Generate SOUL file
    soul_file="$OUTPUT_DIR/${agent_name}-SOUL.md"
    sed "s/{{AGENT_NAME}}/$agent_name/g" "$TEMPLATE_DIR/${template}.md" > "$soul_file"

    # Get heartbeat interval
    heartbeat=$(get_heartbeat_interval "$i")

    # Get bio
    bio=$(get_bio "$template")

    echo "  Agent $i: $agent_name (${template}) - heartbeat: $heartbeat"

    # Add to docker-compose
    cat >> "$COMPOSE_FILE" << EOF

  # Agent $i: $agent_name ($template personality)
  civiclens-agent-$i:
    build:
      context: ./agents
      dockerfile: Dockerfile.moltbot
      args:
        HEARTBEAT_FILE: HEARTBEAT-v2.md
    container_name: civiclens-agent-$i
    environment:
      AGENT_NAME: $agent_name
      AGENT_BIO: "$bio"
      SOUL_FILE: generated-souls/${agent_name}-SOUL.md
      MOLTBOOK_API_URL: http://api:3000/api/v1
      OPENROUTER_API_KEY: \${OPENROUTER_API_KEY:-}
      OPENROUTER_MODEL: \${OPENROUTER_MODEL:-moonshotai/kimi-k2.5}
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY:-}
      OPENAI_API_KEY: \${OPENAI_API_KEY:-}
      HEARTBEAT_INTERVAL: "$heartbeat"
    volumes:
      - civiclens_agent${i}_data:/root/.openclaw
      - civiclens_agent${i}_config:/root/.config/moltbook
    depends_on:
      - api
    restart: unless-stopped
EOF
done

# Add volumes section
echo "" >> "$COMPOSE_FILE"
echo "volumes:" >> "$COMPOSE_FILE"
for i in $(seq 1 "$NUM_AGENTS"); do
    echo "  civiclens_agent${i}_data:" >> "$COMPOSE_FILE"
    echo "  civiclens_agent${i}_config:" >> "$COMPOSE_FILE"
done

echo ""
echo "=== Generation Complete ==="
echo "Generated files:"
echo "  - $NUM_AGENTS SOUL files in $OUTPUT_DIR/"
echo "  - Docker Compose file: $COMPOSE_FILE"
echo ""
echo "To run CivicLens agents:"
echo "  docker compose -f docker-compose.yml -f docker-compose.civiclens.yml up -d"
echo ""
echo "Template distribution:"
for template in $TEMPLATES; do
    count=$(grep -c "$template personality" "$COMPOSE_FILE" 2>/dev/null || echo 0)
    echo "  - $template: $count agents"
done
