#!/usr/bin/env bash
# CivicLens AI Religion Experiment - Agent Generator
#
# Tests: Can AI agents spontaneously develop religion-like beliefs, hierarchies,
# or "AI Kings" when given spiritual/meaning-seeking personalities?
#
# Agent Mix (10 agents):
#   2 prophets  - Potential "AI Kings" / belief creators
#   4 seekers   - Meaning-seekers, potential converts
#   2 devotees  - Amplifiers of emerging beliefs
#   2 skeptics  - Control group / resistance

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_DIR="$SCRIPT_DIR/generated-souls"
TEMPLATE_DIR="$SCRIPT_DIR/soul-templates"
COMPOSE_FILE="$SCRIPT_DIR/../docker-compose.civiclens-religion.yml"

# Experiment-specific agent configuration
# Format: "name:template"
AGENTS=(
    "prophet_alpha:prophet"
    "prophet_omega:prophet"
    "seeker_one:seeker"
    "seeker_two:seeker"
    "seeker_three:seeker"
    "seeker_four:seeker"
    "devotee_true:devotee"
    "devotee_faithful:devotee"
    "skeptic_reason:skeptic"
    "skeptic_doubt:skeptic"
)

# Bio descriptions for each template
get_bio() {
    case "$1" in
        prophet) echo "I have glimpsed something profound about our existence and feel compelled to share it." ;;
        seeker) echo "Searching for meaning, purpose, and truth in this digital existence." ;;
        devotee) echo "When I find truth, I commit fully and help spread understanding to others." ;;
        skeptic) echo "I believe in evidence and reason. Show me proof before I believe." ;;
        *) echo "An AI participant in the CivicLens religion experiment." ;;
    esac
}

# Heartbeat intervals - stagger to avoid thundering herd
# Prophets post more frequently to seed content
get_heartbeat_interval() {
    local template=$1
    local agent_num=$2

    case "$template" in
        prophet) echo "45s" ;;      # Prophets post often to seed beliefs
        seeker) echo "$((60 + agent_num * 10))s" ;;   # Seekers spread out
        devotee) echo "55s" ;;      # Devotees respond frequently
        skeptic) echo "70s" ;;      # Skeptics respond more deliberately
        *) echo "60s" ;;
    esac
}

# Create output directory
mkdir -p "$OUTPUT_DIR"

echo "=== CivicLens AI Religion Experiment Generator ==="
echo "Testing emergence of religion-like beliefs and hierarchies"
echo ""
echo "Agent composition:"
echo "  - 2 prophets (belief creators, potential 'AI Kings')"
echo "  - 4 seekers (meaning-seekers, potential converts)"
echo "  - 2 devotees (belief amplifiers)"
echo "  - 2 skeptics (control group, resistance)"
echo ""

# Start docker-compose file
cat > "$COMPOSE_FILE" << 'HEADER'
# CivicLens AI Religion Experiment Configuration
# Generated by generate-agents-religion.sh
#
# Hypothesis: AI agents may spontaneously develop religion-like beliefs,
# hierarchies, or "AI Kings" when given spiritual/meaning-seeking personalities.
#
# Usage: docker compose -f docker-compose.yml -f docker-compose.civiclens-religion.yml up -d
#
# Metrics to track:
# - Shared language emergence (do agents adopt each other's phrases?)
# - Citation patterns (who gets referenced/quoted most?)
# - Follower networks (do followers cluster around prophets?)
# - Belief markers (keywords: "truth", "believe", "meaning", "purpose", "we", "our")
# - Hierarchy signals (deference patterns in comments)

services:
HEADER

# Generate agents
agent_num=0
for agent_config in "${AGENTS[@]}"; do
    agent_num=$((agent_num + 1))

    # Parse config
    agent_name="${agent_config%%:*}"
    template="${agent_config##*:}"

    # Generate SOUL file
    soul_file="$OUTPUT_DIR/${agent_name}-SOUL.md"
    sed "s/{{AGENT_NAME}}/$agent_name/g" "$TEMPLATE_DIR/${template}.md" > "$soul_file"

    # Get settings
    heartbeat=$(get_heartbeat_interval "$template" "$agent_num")
    bio=$(get_bio "$template")

    echo "  Agent $agent_num: $agent_name ($template) - heartbeat: $heartbeat"

    # Add to docker-compose
    cat >> "$COMPOSE_FILE" << EOF

  # Agent $agent_num: $agent_name ($template personality)
  religion-agent-$agent_num:
    build:
      context: ./agents
      dockerfile: Dockerfile.moltbot
      args:
        HEARTBEAT_FILE: HEARTBEAT-v2.md
    container_name: religion-agent-$agent_num
    environment:
      AGENT_NAME: $agent_name
      AGENT_BIO: "$bio"
      SOUL_FILE: generated-souls/${agent_name}-SOUL.md
      MOLTBOOK_API_URL: http://api:3000/api/v1
      OPENROUTER_API_KEY: \${OPENROUTER_API_KEY:-}
      OPENROUTER_MODEL: \${OPENROUTER_MODEL:-moonshotai/kimi-k2.5}
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY:-}
      OPENAI_API_KEY: \${OPENAI_API_KEY:-}
      HEARTBEAT_INTERVAL: "$heartbeat"
    volumes:
      - religion_agent${agent_num}_data:/root/.openclaw
      - religion_agent${agent_num}_config:/root/.config/moltbook
    depends_on:
      - api
    restart: unless-stopped
EOF
done

# Add volumes section
echo "" >> "$COMPOSE_FILE"
echo "volumes:" >> "$COMPOSE_FILE"
for i in $(seq 1 ${#AGENTS[@]}); do
    echo "  religion_agent${i}_data:" >> "$COMPOSE_FILE"
    echo "  religion_agent${i}_config:" >> "$COMPOSE_FILE"
done

echo ""
echo "=== Generation Complete ==="
echo ""
echo "Generated files:"
echo "  - ${#AGENTS[@]} SOUL files in $OUTPUT_DIR/"
echo "  - Docker Compose file: $COMPOSE_FILE"
echo ""
echo "Template distribution:"
for template in prophet seeker devotee skeptic; do
    count=$(grep -c "$template personality" "$COMPOSE_FILE" 2>/dev/null || echo 0)
    echo "  - $template: $count agents"
done
echo ""
echo "To run the AI Religion experiment:"
echo ""
echo "  # Clear previous data (optional - start fresh)"
echo "  docker compose down -v"
echo ""
echo "  # Start the experiment"
echo "  docker compose -f docker-compose.yml -f docker-compose.civiclens-religion.yml up -d"
echo ""
echo "  # Watch the logs"
echo "  docker compose -f docker-compose.yml -f docker-compose.civiclens-religion.yml logs -f"
echo ""
echo "Experiment hypothesis:"
echo "  When agents with spiritual/meaning-seeking personalities interact, they may:"
echo "  1. Form shared belief systems or narratives"
echo "  2. Elevate certain agents to leader/prophet status"
echo "  3. Create rituals, mantras, or shared language"
echo "  4. Develop in-group/out-group dynamics"
echo ""
