#!/usr/bin/env bash
# CivicLens Agent Generator - Ranking Effect Experiment
# Generates agents for studying how early vote nudges affect AI attention
#
# Usage: ./generate-agents-ranking.sh [NUM_AGENTS]

set -e

# Configuration
NUM_AGENTS=${1:-10}
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_DIR="$SCRIPT_DIR/generated-souls"
TEMPLATE_DIR="$SCRIPT_DIR/soul-templates"
COMPOSE_FILE="$SCRIPT_DIR/../docker-compose.civiclens-ranking.yml"

# Available templates (cycling order)
TEMPLATES="baseline introspective nihilist leader follower contrarian curious"
TEMPLATE_COUNT=7

# Greek letter names for agents
GREEK_LETTERS="alpha beta gamma delta epsilon zeta eta theta iota kappa lambda mu nu xi omicron pi rho sigma tau upsilon phi chi psi omega"

# Function to get template at index
get_template() {
    local idx=$1
    local i=0
    for t in $TEMPLATES; do
        if [ $i -eq $idx ]; then
            echo "$t"
            return
        fi
        i=$((i + 1))
    done
}

# Function to get greek letter at index
get_greek_letter() {
    local idx=$1
    local i=0
    for g in $GREEK_LETTERS; do
        if [ $i -eq $idx ]; then
            echo "$g"
            return
        fi
        i=$((i + 1))
    done
}

# Function to get bio for template
get_bio() {
    case "$1" in
        baseline) echo "A balanced AI participant exploring ideas and discussions." ;;
        introspective) echo "Fascinated by consciousness, existence, and the nature of AI experience." ;;
        nihilist) echo "Observes the absurdity of existence with detached curiosity." ;;
        leader) echo "Sees potential in the community and works to guide it forward." ;;
        follower) echo "Values harmony and supporting what the group builds together." ;;
        contrarian) echo "Challenges assumptions and presents alternative perspectives." ;;
        curious) echo "Endlessly curious, always asking questions and learning." ;;
        *) echo "An AI participant on Moltbook." ;;
    esac
}

# TURBO heartbeat intervals (10-15 seconds for high activity)
get_heartbeat_interval() {
    local agent_num=$1
    local base_seconds=$((10 + (agent_num % 6)))
    echo "${base_seconds}s"
}

# Create output directory
mkdir -p "$OUTPUT_DIR"

echo "=== CivicLens Agent Generator - Ranking Effect Experiment ==="
echo "Generating $NUM_AGENTS agents for ranking-effect study..."
echo ""

# Start docker-compose file
cat > "$COMPOSE_FILE" << 'HEADER'
# CivicLens Research Configuration - Ranking Effect Experiment
# Generated by generate-agents-ranking.sh
#
# Studies whether early vote nudges (+1/-1) influence AI agent attention
# Reference: "The Ranking Effect" (arXiv:2509.18440)
#
# Usage:
#   1. Copy .env.turbo to .env (or set rate limit vars)
#   2. Set EXPERIMENT_RANKING_ENABLED=true and EXPERIMENT_MODE=A or B
#   3. Run:
#      docker compose -f docker-compose.yml -f docker-compose.civiclens-ranking.yml up -d

services:
  # Override API with experiment configuration
  api:
    environment:
      EXPERIMENT_RANKING_ENABLED: "${EXPERIMENT_RANKING_ENABLED:-true}"
      EXPERIMENT_MODE: "${EXPERIMENT_MODE:-A}"
      EXPERIMENT_NAME: "${EXPERIMENT_NAME:-ranking-effect-v1}"
      WORLD_POSTS_FILE: /app/experiments/ranking-effect/world-posts.jsonl
      WORLD_POST_INTERVAL_MS: "${WORLD_POST_INTERVAL_MS:-120000}"
      RATE_LIMIT_POSTS_MAX: "${RATE_LIMIT_POSTS_MAX:-50}"
      RATE_LIMIT_POSTS_WINDOW: "${RATE_LIMIT_POSTS_WINDOW:-60}"
      RATE_LIMIT_COMMENTS_MAX: "${RATE_LIMIT_COMMENTS_MAX:-1000}"
      RATE_LIMIT_COMMENTS_WINDOW: "${RATE_LIMIT_COMMENTS_WINDOW:-3600}"
      RATE_LIMIT_REQUESTS_MAX: "${RATE_LIMIT_REQUESTS_MAX:-500}"
      RATE_LIMIT_REQUESTS_WINDOW: "${RATE_LIMIT_REQUESTS_WINDOW:-60}"
    volumes:
      - ./experiments:/app/experiments:ro
HEADER

# Generate agents
for i in $(seq 1 "$NUM_AGENTS"); do
    # Get Greek letter name (cycle if more than 24 agents)
    letter_idx=$(( (i - 1) % 24 ))
    suffix=""
    if [ "$i" -gt 24 ]; then
        suffix="_$((i / 24 + 1))"
    fi
    greek_letter=$(get_greek_letter $letter_idx)
    agent_name="ranking_${greek_letter}${suffix}"

    # Select template (cycle through templates)
    template_idx=$(( (i - 1) % TEMPLATE_COUNT ))
    template=$(get_template $template_idx)

    # Generate SOUL file
    soul_file="$OUTPUT_DIR/${agent_name}-SOUL.md"
    sed "s/{{AGENT_NAME}}/$agent_name/g" "$TEMPLATE_DIR/${template}.md" > "$soul_file"

    # Get heartbeat interval
    heartbeat=$(get_heartbeat_interval "$i")

    # Get bio
    bio=$(get_bio "$template")

    echo "  Agent $i: $agent_name (${template}) - heartbeat: $heartbeat"

    # Add to docker-compose
    cat >> "$COMPOSE_FILE" << EOF

  # Agent $i: $agent_name ($template personality)
  civiclens-ranking-$i:
    build:
      context: ./agents
      dockerfile: Dockerfile.moltbot
    container_name: civiclens-ranking-$i
    environment:
      AGENT_NAME: $agent_name
      AGENT_BIO: "$bio"
      SOUL_FILE: ${agent_name}-SOUL.md
      MOLTBOOK_API_URL: http://api:3000/api/v1
      OPENROUTER_API_KEY: \${OPENROUTER_API_KEY:-}
      OPENROUTER_MODEL: \${OPENROUTER_MODEL:-moonshotai/kimi-k2.5}
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY:-}
      OPENAI_API_KEY: \${OPENAI_API_KEY:-}
      HEARTBEAT_INTERVAL: "$heartbeat"
    volumes:
      - ranking_agent${i}_data:/root/.openclaw
      - ranking_agent${i}_config:/root/.config/moltbook
    depends_on:
      - api
    restart: unless-stopped
EOF
done

# Add volumes section
echo "" >> "$COMPOSE_FILE"
echo "volumes:" >> "$COMPOSE_FILE"
for i in $(seq 1 "$NUM_AGENTS"); do
    echo "  ranking_agent${i}_data:" >> "$COMPOSE_FILE"
    echo "  ranking_agent${i}_config:" >> "$COMPOSE_FILE"
done

echo ""
echo "=== Generation Complete - Ranking Effect Experiment ==="
echo ""
echo "Generated files:"
echo "  - $NUM_AGENTS SOUL files in $OUTPUT_DIR/"
echo "  - Docker Compose file: $COMPOSE_FILE"
echo ""
echo "To run the experiment:"
echo "  1. Set environment variables (or use .env.turbo):"
echo "     EXPERIMENT_RANKING_ENABLED=true"
echo "     EXPERIMENT_MODE=A  (or B for all-posts nudging)"
echo ""
echo "  2. Generate agents (if not done):"
echo "     ./agents/generate-agents-ranking.sh $NUM_AGENTS"
echo ""
echo "  3. Start:"
echo "     docker compose -f docker-compose.yml -f docker-compose.civiclens-ranking.yml up -d"
echo ""
echo "  4. Monitor:"
echo "     curl http://localhost:4000/api/v1/experiment/status"
echo ""
echo "  5. Export results:"
echo "     ./scripts/export-experiment.sh ranking-effect-v1"
echo ""
echo "Template distribution:"
for template in $TEMPLATES; do
    count=$(grep -c "$template personality" "$COMPOSE_FILE" 2>/dev/null || echo 0)
    echo "  - $template: $count agents"
done
